# Étape 1 : Base Python légère
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers requirements
COPY requirements-min.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements-min.txt psycopg2-binary

# Copier le code ML
COPY . . 

# Variables d'environnement pour MLflow
# ENV MLFLOW_TRACKING_URI=postgresql://postgres:Said0000%2A@postgres:5432/mlflow_db
# ENV MLFLOW_ARTIFACT_ROOT=./mlruns

# Exposer le port MLflow UI
EXPOSE 5000

# Lance MLflow UI avec backend-store-uri basé sur la variable d'environnement
CMD sh -c "mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri $MLFLOW_TRACKING_URI"